Better error information & A possible better way to enter password.
iMyOwn/ipgw pull request #57
Opened 2024-10-01 18:09 UTC by stceum

- 更好的错误信息显示

  之前：
  ```shell
  $ ipgw login -u xxxxxxx
  login failed:
        unknown reason
  ```

  现在：
  显示来自 `https://ipgw.neu.edu.cn/v1/srun_portal_sso?ac_id=1&ticket=ST-xxxxxxxx-xxxxxxxxxxxxxxxxxx-tpass` 的响应 json 的 `message`
   ```shell
  $ ipgw login -u xxxxxxx
  login failed:
        E2606: User is disabled.
  ```

- 一种可能更好的输入密码的方式。

  之前：（需要密码，该密码可能存在于 bash/zsh/... 历史记录中）：
  ```shell
  $ ipgw config account add -u xxxxxxx -p xxx...xxx # 可能不安全
  ```
  现在：
  ```shell
  $ ipgw config account add -u xxxxxxx
  Enter Password: # 输入时不回显
  ```

---

- Better error information

  previous:
  ```shell
  $ ipgw login -u xxxxxxx
  login failed:
        unknown reason
  ```
  
  current:
  show `message` from response json of `https://ipgw.neu.edu.cn/v1/srun_portal_sso?ac_id=1&ticket=ST-xxxxxxxx-xxxxxxxxxxxxxxxxxxxx-tpass`
   ```shell
  $ ipgw login -u xxxxxxx
  login failed:
        E2606: User is disabled.
  ```

- A possible better way to enter password.

  previous (password is required which may exist in the bash/zsh/... history):
  ```shell
  $ ipgw config account add -u xxxxxxx -p xxx...xxx # Potentially unsafe
  ```

  current:
  ```shell
  $ ipgw config account add -u xxxxxxx
  Enter Password: # type in without echo
  ```

2024-10-06 15:09 UTC, unbyte requested changes
最好拆成两个 pr，一个改错误信息一个增加密码的输入方式

2024-10-06 15:09 UTC, unbyte commented on pkg/handler/ipgw.go
> +	parseLoginResponseErr := json.Unmarshal([]byte(body), &loginResponse)
wow 现在返回的已经是 json 了吗，那下面的几个报错的 case 需要跟着改吗

2024-10-07 04:05 UTC, stceum commented on pkg/handler/ipgw.go
> +	parseLoginResponseErr := json.Unmarshal([]byte(body), &loginResponse)
是的！例如下面登录失败的
```json
{"code":1,"message":"E2606: User is disabled.","Redirect":"","ID":"1"}
```
以及登陆成功的
```json
{"code":0,"message":"success","Redirect":"","ID":"1"}
```
真实登录页面提示的错误应该是根据响应的 json 里面的 `message` 找到对应的翻译在前端弹窗提示，有一个 [lang.js](https://ipgw.neu.edu.cn/static/themes/pro/js/lang.js) 应该包含了所有的错误，所以下面基于字符串匹配的报错应该不需要了

------

以防校外无法访问，附 `lang.js` 内容如下：
```js
var translate = {
    'zh-CN': {
        H: "时",
        M: "分",
        S: "秒",
        E0000: "登录成功",
        E2401: "User-Request",
        E2402: "Lost-Carrier",
        E2404: "Idle-Timeout",
        E2405: "Session-Timeout",
        E2406: "Admin-Reset",
        E2407: "Admin-Reboot",
        E2408: "Port-Error",
        E2409: "NAS-Error",
        E2410: "NAS-Request",
        E2411: "NAS-Reboot",
        E2412: "Port-Unneeded",
        E2413: "Port-Preempted",
        E2414: "Port-Suspended",
        E2415: "Service-Unavailable",
        E2416: "Callback",
        E2417: "User-Error",
        E2531: "用户不存在",
        E2532: "您的两次认证的间隔太短,请稍候10秒后再重试登录",
        E2533: "密码错误次数超过限制，请5分钟后再重试登录",
        E2534: "有代理行为被暂时禁用",
        E2535: "认证系统已经被禁用",
        E2536: "授权已过期",
        E2553: "帐号或密码错误",
        E2601: "您使用的不是专用客户端,IPOE-PPPoE混杂模式请联系管理员重新打包客户端程序",
        E2602: "您还没有绑定手机号或绑定的非联通手机号码",
        E2606: "用户被禁用",
        E2607: "接口被禁用",
        E2611: "您当前使用的设备非该账号绑定设备 请绑定或使用绑定的设备登入",
        E2613: "NAS PORT绑定错误",
        E2614: "MAC地址绑定错误",
        E2615: "IP地址绑定错误",
        E2616: "用户已欠费",
        E2620: "已经在线了",
        E2621: "已经达到授权人数",
        E2806: "找不到符合条件的产品",
        E2807: "找不到符合条件的计费策略",
        E2808: "找不到符合条件的控制策略",
        E2833: "IP不在DHCP表中，需要重新拿地址。",
        E2840: "校内地址不允许访问外网",
        E2841: "IP地址绑定错误",
        E2842: "IP地址无需认证可直接上网",
        E2843: "IP地址不在IP表中",
        E2844: "IP地址在黑名单中",
        E2901: "第三方认证接口返回的错误信息",
        /*extend translate*/
        E6500: "认证程序未启动",
        E6501: "用户名输入错误",
        E6502: "注销时发生错误，或没有帐号在线",
        E6503: "您的账号不在线上",
        E6504: "注销成功，请等1分钟后登录",
        E6505: "您的MAC地址不正确",
        E6506: "用户名或密码错误，请重新输入",
        E6507: "您无须认证，可直接上网",
        E6508: "您已欠费，请尽快充值",
        E6509: "您的资料已被修改正在等待同步，请2钟分后再试。如果您的帐号允许多个用户上线，请到WEB登录页面注销",
        E6510: "您的帐号已经被删除",
        E6511: "IP已存在，请稍后再试",
        E6512: "在线用户已满，请稍后再试",
        E6513: "正在注销在线账号，请重新连接",
        E6514: "你的IP地址和认证地址不附，可能是经过小路由器登录的",
        E6515: "系统已禁止客户端登录，请使用WEB方式登录",
        E6516: "您的流量已用尽",
        E6517: "您的时长已用尽",
        E6518: "您的IP地址不合法，可能是:一、与绑的IP地址附；二、IP不允许在当前区域登录",
        E6519: "当前时段不允许连接",
        E6520: "抱歉，您的帐号已禁用",
        E6521: "您的IPv6地址不正确，请重新配置IPv6地址",
        E6522: "客户端时间不正确，请先同步时间（或者是调用方传送的时间格式不正确，不是时间戳；客户端和服务器之间时差超过2小时，括号里面内容不要提示给客户）",
        E6523: "认证服务无响应",
        E6524: "计费系统尚未授权，目前还不能使用",
        E6525: "后台服务器无响应;请联系管理员检查后台服务运行状态",
        E6526: "您的IP已经在线;可以直接上网;或者先注销再重新认证",
        E6527: "当前设备不在线",
        E6528: "您已经被服务器强制下线",
        E6529: "身份验证失败，但不返回错误消息",
        E10015: "短信发送太频繁，请一分钟后重试",
        E10016: "今天短信发送次数已用完",
        E10039: "访客账号的使用次数已超过最大限制",
        // error message
        E3001: "流量或时长已用尽",
        E3002: "计费策略条件不匹配",
        E3003: "控制策略条件不匹配",
        E3004: "余额不足",
        E3005: "在线变更计费策略",
        E3006: "在线变更控制策略",
        E3007: "超时",
        E3008: "连线数超额，挤出在线表。",
        E3009: "有代理行为",
        E3010: "无流量超时",
        E3101: "心跳包超时",
        E4001: "Radius表DM下线",
        E4002: "DHCP表DM下线",
        E4003: "Juniper IPOE COA上线",
        E4004: "Juniper IPOE COA下线",
        E4005: "proxy表DM下线",
        E4006: "COA在线更改带宽",
        E4007: "本地下线",
        E4008: "虚拟下线",
        E4009: "策略切换时下发COA",
        E4011: "结算时虚拟下线",
        E4012: "下发COA",
        E4101: "来自radius模块的DM下线（挤出在线表）",
        E4102: "来自系统设置（8081）的DM下线",
        E4103: "来自后台管理（8080）的DM下线",
        E4104: "来自自服务（8800）的DM下线",
        E4112: "来自系统设置（8081）的本地下线",
        E4113: "来自后台管理（8080）的本地下线",
        E4114: "来自自服务（8800）的本地下线",
        E4122: "来自系统设置（8081）的虚拟下线",
        E4123: "来自后台管理（8080）的虚拟下线",
        E4124: "来自自服务（8800）的虚拟下线",
        E2554: "EAP校验失败",
        E2555: "未绑定运营商帐号",
        E2612: "MAC在黑名单中",
        E2617: "消费额度已满",
        E5990: "数据不完整",
        E5991: "无效的参数",
        E5992: "找不到这个用户",
        E5993: "用户已存在",
        E5001: "用户创建成功",
        E5002: "用户创建失败",
        E5010: "修改用户成功",
        E5011: "修改用户失败",
        E5020: "修改用户成功",
        E5021: "修改用户失败",
        E5030: "转组成功",
        E5031: "转组失败",
        E5040: "购买套餐成功",
        E5041: "购买套餐失败",
        E5042: "找不到套餐",
        E5050: "绑定MAC认证成功",
        E5051: "解绑MAC认证成功",
        E5052: "绑定MAC成功",
        E5053: "解绑MAC成功",
        E5054: "绑定nas port成功",
        E5055: "解绑nas port成功",
        E5056: "绑定vlan id成功",
        E5057: "解绑vlan id成功",
        E5058: "绑定ip成功",
        E5059: "解绑ip成功",
        E6001: "用户缴费成功",
        E6002: "用户缴费失败",
        //结算日志
        E7001: "用户不存在",
        E7002: "添加待结算队列失败",
        E7003: "结算成功",
        E7004: "添加已结算队列失败",
        E7005: "扣除产品实例结算金额失败",
        E7006: "没有找到产品实例",
        E7007: "没有对该用户进行手动结算的权限",
        E7008: "没有对该产品进行手动结算的权限",
        E7009: "由于使用流量小于该产品结算设置而不扣费",
        E7010: "由于使用时长小于该产品结算设置而不扣费",
        E7011: "由于产品余额不足，根据结算设置而不扣费",
        E7012: "由于产品余额不足，根据结算设置余额扣为0",
        E7013: "由于产品余额不足，根据结算设置余额扣为负值",
        E7014: "删除过期套餐操作成功",
        E7015: "删除过期套餐操作失败",
        E7016: "自动购买套餐成功",
        E7017: "自动购买套餐失败",
        E7018: "产品结算模式错误",
        //new translate
        ChallengeExpireError: "Challenge时间戳错误",
        SignError: "签名错误",
        NotOnlineError: "当前设备不在线",
        VcodeError: "验证码错误",
        SpeedLimitError: "认证请求太频繁，请稍后10s重试",
        SrunPortalServerError: "Portal服务请求错误",
        AuthResaultTimeoutErr: "Portal服务请求超时",
        IpAlreadyOnlineError: "本机IP已经使用其他账号登陆在线了",
        MemoryDbError: "SRun认证服务(srun_portal_server)无响应",
        GetVerifyCode: "获取验证码",
        CasUsernameIsEmpty: "获取CAS用户名失败",
        ProvisionalReleaseFail: "临时放行失败",
        INFOFailedBASRespondTimeout: "BAS无响应",
        LogoutOK: "DM下线成功",
        SendVerifyCodeOK: "验证码发送成功",
        PhoneNumberError: "手机号错误",
        IsEvokingWeChat: "正在唤起微信...",
        Info: "信息",
        OK: "确认",
        CheckServerTimestamp: "检查服务器时间",
        TimestampError: "时间戳错误",
        TypeError: "加密类型错误",
        VerifyCodeError: "验证码错误",
        ACIDIsRequired: "缺少ACID",
        TypeIsEmptyOrError: "微信请求类型为空或错误",
        ACIDIsEmpty: "缺少ACID",
        BSSIDIsEmpty: "缺少BSSID",
        MACIsEmpty: "缺少MAC",
        TokenIsEmpty: "缺少Token",
        WeChatOptionNotFound: "未找到微信配置",
        CreateVisitorError: "创建访客失败",
        NoResponseDataError: "登录超时，请重新登录",
        VcodeTooOftenError: "两次间隔时间太短",
        Wait: "请稍等...",
        YouAreNotOnline: "该设备不在线",
        NasTypeNotFound: "NAS设备不存在",
        UserMustModifyPassword: "您的密码比较简单或已长时间未修改，存在安全隐患，请登录自服务重置您的密码",
        AuthInfoError: "刷新页面后再次登录",
        TokenError: "验证码发送失败",
        MissingRequiredParametersError: "登录失败，请联系网络管理员",
        NoAcidError: "网络设备出问题，请稍候",
        OtpServerError: "身份验证器服务故障",
        OtpCodeCheckError: "口令验证失败",
        OtpCodeHasBeenUsed: "动态码已被使用",
        "E2901:(ThirdParty1)bindUser2:LdapBindError": "账号或密码错误",
        "E2901:(ThirdParty1)ldapFirstEntryError": "账号或密码错误",
        "CHALLENGEFailedBASRespondTimeout": "网络连接超时，请稍后重试",
        "INFOError锛宔rrCode=2": "设备不在认证范围内",
        "TheServerIsNotResponding": "服务等待超时，请稍后重试",
        LimitDomainErr: "请使用中科院允许的邮箱进行登录",
        BxResaultTimeoutErr: "北向接口服务器异常，请查看日志或检查北向接口服务",
        BxAddUserErr: "添加用户失败，请联系管理员",
        ZkNetworkError: "科技云服务异常",
        ZkUserError: "登录中国科技云通行证的账号无效，请检查账号是否正确",
        BrowserVersionError: "请使用 Chrome 浏览器或 360 浏览器极速模式",
        SsoServerError: "单点登陆服务异常，请检查服务",
        IPHasBeenOnlinePleaseLogout: "您的设备已经在线，不可重复提交",
        UserDoesNotExist: "该手机号未注册",
        MysqlConnectPoolIsNil: "数据库连接池为空",
        UserDoesNotExistInWhiteList: "用户不存在于白名单中",
        VisitorCoolingError: "账号已过期",
        // portal
        Username: '用户账号',
        Rea [...]

2024-10-07 04:06 UTC, stceum commented on pkg/handler/ipgw.go
> +	parseLoginResponseErr := json.Unmarshal([]byte(body), &loginResponse)
了解，我拆成两个pr提交~

2024-10-07 04:06 UTC, closed without merging